language: node_js
dist: xenial
os: linux
node_js:
  - node
  - lts/*
install:
  - rm -rf node_modules && yarn install --frozen-lockfile
script:
  - yarn lint:sass-fix
  - yarn lint:sass
  - yarn lint:js
deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist
  on:
    branch: master
    node_js: 'lts/*'
