GET http://localhost:7070/api/movies/5fb2b0539ad69859a2e1bb94 HTTP/1.1

### 
GET http://localhost:7070/api/movies HTTP/1.1

###
POST http://localhost:7070/api/movies/utils/postSampleDatasets HTTP/1.1

###
GET http://localhost:7070/api/theaters/5fb2b0539ad69859a2e1bb94 HTTP/1.1

### 
GET http://localhost:7070/api/theaters HTTP/1.1

###
POST http://localhost:7070/api/theaters/utils/postSampleDatasets HTTP/1.1

###
GET http://localhost:7070/api/theaters_movies HTTP/1.1

###
GET http://localhost:6969/api/theaters_movies/findByMovie/5fb775d63a360279a974f5eb HTTP/1.1

###
GET http://localhost:6969/api/theaters_movies/findRecursively/5fc732357d9b6de99302e7ba HTTP/1.1

###
POST http://localhost:7070/api/theaters_movies/utils/postSampleDatasets HTTP/1.1

###
GET http://localhost:7070/api/showTimes/ HTTP/1.1

###
GET http://localhost:6969/showtimes/allShowtimes/5fc732357d9b6de99302e7ba HTTP/1.1

###
POST http://localhost:7070/api/showTimes/utils/postSampleDatasets HTTP/1.1

###
GET http://localhost:6969/feature/getShowtimesByTheaterMovie/5fc388cbfb279b6e908d5ac2 HTTP/1.1